FROM openjdk:8-jre
COPY ./target/xkeys_si-0.0.1-SNAPSHOT-jar-with-dependencies.jar xkeys_si-0.0.1-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 8081
CMD ["java", "-jar", "xkeys_si-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]
